- name: "yum install local test perl depdendencies"
  include_role:
    name: yum_retry
  vars:
    package:
      - perl-Test-Harness
      - perl-ExtUtils-Manifest
      - perl-ExtUtils-Install
      - diffutils
- lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: 'LANG=C.utf8'
