---
- hosts: all
  roles:
    - role: common
    - role: thruk_developer
  tasks:
  - name: "omd config change"
    shell: "omd config demo change"
    args:
      stdin: |
        APACHE_MODE=own
  - shell: rm /omd/sites/demo/etc/naemon/conf.d/*.cfg
  - shell: ln -s /thruk/support/thruk_templates.cfg /omd/sites/demo/etc/naemon/conf.d/thruk_templates.cfg
  - copy:
      src: /root/test.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/test.cfg
      owner: demo
      group: demo
  - lineinfile:
      path: /omd/sites/demo/etc/naemon/resource.cfg
      line: '$USER5$=;'
  - copy:
      src: /root/thruk_extra.conf
      dest: /omd/sites/demo/etc/thruk/thruk_local.d/
      owner: demo
      group: demo
  - name: remove Apache Content-Security-Policy
    lineinfile: dest=/omd/sites/demo/etc/thruk/apache.conf
                state=absent
                regexp='Content-Security-Policy'
