---
- hosts: all
  roles:
    - role: common
    - role: thruk_developer
  tasks:
  - name: "yum install perl depdendencies of Dancer2::Plugin::OAuth2::Server"
    yum:
      name:
        - gcc
        - perl-Class-Load
        - perl-URI
        - perl-Plack-Test
        - perl-Module-Metadata
        - perl-Type-Tiny
        - perl-Hash-Merge-Simple
        - perl-Safe-Isa
        - perl-Role-Tiny
        - perl-Test-CPAN-Meta
        - perl-Attribute-Handlers
        - perl-Getopt-Long-Descriptive
        - perl-Config-Any
        - perl-Import-Into
        - perl-Ref-Util
        - perl-App-cpanminus
      state: present
    register: result
    retries: 30
    until: result is succeeded
    delay: 10
  - name: "omd config change"
    shell: "omd config demo change"
    args:
      stdin: |
        APACHE_MODE=own
        GRAFANA=on
        LIVESTATUS_TCP=on
  - copy:
      src: /omd/sites/demo/share/doc/naemon/example.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/example.cfg
      owner: demo
      group: demo
  - copy:
      src: /root/thruk_local.conf
      dest: /omd/sites/demo/etc/thruk/thruk_local.conf
      owner: demo
      group: demo
  - copy:
      src: /root/grafana.ini
      dest: /omd/sites/demo/etc/grafana/grafana.ini
      owner: demo
      group: demo
  - shell: cpanm -n Dancer2::Plugin::OAuth2::Server
  - shell: sudo su - demo -c "( plackup -D -p 4444 /scenario/omd/oauth2_server/oauth2_server.pl >/dev/null 2>&1 & )"
