- stat: path=/usr/bin/make
  register: make_path
- stat: path=/usr/bin/git
  register: git_path
- stat: path=/usr/share/perl5/vendor_perl/ExtUtils/Manifest.pm
  register: manifest_path
- name: "install perl / git dependencies"
  yum:
    name:
      - perl-ExtUtils-Manifest
      - perl-ExtUtils-Install
      - git-core
      - make
    state: present
  register: result
  retries: 30
  until: result is succeeded
  delay: 10
  # hack because ansibles takes over 10seconds, even if it does not install anything
  when: not make_path.stat.exists or not git_path.stat.exists or not manifest_path.stat.exists

- stat: path=/usr/lib/locale/en_US.utf8
  register: locale_path
- name: "glibc-langpack-en when rhel >= 8"
  yum:
    name:
      - glibc-langpack-en
    state: present
  when: not locale_path.stat.exists and ansible_distribution_version|int >= 8
  register: result
  retries: 30
  until: result is succeeded
  delay: 10

- name: "install File::ChangeNotify"
  shell: "sudo su - {{ site }} -c 'cpanm -n File::ChangeNotify'"
  args:
    creates: "/omd/sites/{{ site }}/local/lib/perl5/lib/perl5/File/ChangeNotify.pm"

- name: "git clone omd_utils"
  shell: "sudo su - {{ site }} -c 'cd ~/local/share && git clone --depth=1 --branch=master https://github.com/sni/omd_utils.git'"
  args:
    creates: "/omd/sites/{{ site }}/local/share/omd_utils"

- stat: path=/thruk
  register: thruk_path
- name: "run install.sh from omd_utils"
  shell: "sudo su - {{ site }} -c 'yes | ~/local/share/omd_utils/thruk_developer/install.sh /thruk'"
  when: thruk_path.stat.exists
