---
- hosts: all
  roles:
    - role: common
  tasks:
  - copy:
      src: "/omd/sites/demo/share/doc/naemon/example.cfg"
      dest: "/omd/sites/demo/etc/naemon/conf.d/example.cfg"
      owner: "demo"
      group: "demo"
  - name: "yum install stunnel"
    yum:
      name: stunnel
      state: latest
    register: result
    retries: 30
    until: result is succeeded
    delay: 10
  - file:
      src: "/omd/sites/demo/etc/stunnel/xinetd.conf"
      dest: "/omd/sites/demo/etc/xinetd.d/stunnel"
      owner: demo
      group: demo
      state: link
