---
- hosts: all
  roles:
    - role: common
  tasks:
  - copy:
      src: "/omd/sites/demo/share/doc/naemon/example.cfg"
      dest: "/omd/sites/demo/etc/naemon/conf.d/example.cfg"
      owner: "demo"
      group: "demo"
  - name: install stunnel
    include_role:
      name: yum_retry
    vars:
      package: stunnel
  - file:
      src: "/omd/sites/demo/etc/stunnel/xinetd.conf"
      dest: "/omd/sites/demo/etc/xinetd.d/stunnel"
      owner: demo
      group: demo
      state: link
