version: '2'

services:
  omd:
    build: omd/
    ports:
        - "127.0.0.3:60080:80"
    environment:
        - TZ=Europe/Berlin
    volumes:
        - ../../../:/thruk:ro
  sakuli:
    image: ghcr.io/consol/sakuli/sakuli-ubuntu-xfce:dev
    environment:
        - JVM_HEAP_XMX=512
        - TZ=Europe/Berlin
    ports:
        - "127.0.0.3:5901:5901"
    volumes:
        - ./:/thruk:ro
        - ./_run:/cases:rw
    command: --tail-log
