- name: "yum install npm / chrome"
  yum:
    name:
      - npm
      - chromium
      - libxshmfence
    state: present
  register: result
  retries: 30
  until: result is succeeded
  delay: 10
- shell: "sudo su - {{ site }} -c 'npm i puppeteer'"
