- name: "yum install npm / chrome"
  include_role:
    name: yum_apt_retry
  vars:
    package:
      - npm
      - chromium
    rpm:
      - libxshmfence
    deb:
      - libxshmfence1
- shell: "sudo su - {{ site }} -c 'npm i puppeteer'"
